test:
  adapter: postgresql
  encoding: unicode
  database: chitter_test
  pool: 2
  username: anthonyhull
  password:

development:
  adapter: postgresql
  encoding: unicode
  database: chitter
  pool: 2
  username: anthonyhull
  password: